import { TriviaCard } from '@/types'

export const TRIVIA_QUESTIONS: TriviaCard[] = [
  {
    id: 'q001',
    question: 'Ce procent din venit este recomandat să economisești lunar?',
    options: ['5%', '10%', '20%', '30%'],
    correct_index: 2,
    explanation: 'Regula 50/30/20 recomandă alocarea a 20% din venit pentru economii și investiții. Această regulă a fost popularizată de senatoarea americană Elizabeth Warren.',
    category: 'budgeting',
    difficulty: 'easy',
    points: 10,
  },
  {
    id: 'q002',
    question: 'Ce înseamnă dobânda compusă?',
    options: [
      'Dobânda calculată doar pe suma inițială',
      'Dobânda calculată pe suma inițială plus dobânzile acumulate',
      'O dobândă fixă aplicată anual',
      'Dobânda plătită de bancă la depozite',
    ],
    correct_index: 1,
    explanation: 'Dobânda compusă este calculată atât pe suma inițială (principalul), cât și pe dobânzile acumulate anterior. Albert Einstein a numit-o "a opta minune a lumii".',
    category: 'investing',
    difficulty: 'medium',
    points: 15,
  },
  {
    id: 'q003',
    question: 'Care este scopul principal al unui fond de urgență?',
    options: [
      'Investiții pe termen lung',
      'Plata vacanțelor',
      'Acoperirea cheltuielilor neprevăzute timp de 3-6 luni',
      'Cumpărarea de acțiuni',
    ],
    correct_index: 2,
    explanation: 'Un fond de urgență ar trebui să acopere cheltuielile esențiale pentru 3-6 luni (chirie, mâncare, utilități) în cazul pierderii locului de muncă sau a altor situații neprevăzute.',
    category: 'savings',
    difficulty: 'easy',
    points: 10,
  },
  {
    id: 'q004',
    question: 'Ce reprezintă rata DAE (Dobânda Anuală Efectivă)?',
    options: [
      'Doar rata dobânzii nominale',
      'Costul total al creditului exprimat ca procent anual, inclusiv comisioane',
      'Dobânda lunară a creditului',
      'Taxa de administrare a contului',
    ],
    correct_index: 1,
    explanation: 'DAE (Dobânda Anuală Efectivă) include toate costurile unui credit: dobânda nominală, comisioanele și alte taxe, exprimând costul real al împrumutului ca procent anual. Este cel mai bun indicator pentru compararea creditelor.',
    category: 'credit',
    difficulty: 'medium',
    points: 15,
  },
  {
    id: 'q005',
    question: 'Ce este diversificarea unui portofoliu de investiții?',
    options: [
      'Investirea tuturor banilor într-un singur activ',
      'Împărțirea investițiilor în mai multe tipuri de active pentru reducerea riscului',
      'Vânzarea tuturor acțiunilor când piața scade',
      'Investirea doar în aur',
    ],
    correct_index: 1,
    explanation: 'Diversificarea înseamnă distribuirea investițiilor în diferite clase de active (acțiuni, obligațiuni, imobiliare, etc.) și zone geografice pentru a reduce riscul. Dacă un activ scade, altele pot compensa.',
    category: 'investing',
    difficulty: 'easy',
    points: 10,
  },
  {
    id: 'q006',
    question: 'Care este plafonul garantat de FGDB (Fondul de Garantare a Depozitelor Bancare) per deponent?',
    options: ['10.000 EUR', '50.000 EUR', '100.000 EUR', '200.000 EUR'],
    correct_index: 2,
    explanation: 'FGDB garantează depozitele până la echivalentul a 100.000 EUR per deponent, per bancă. Aceasta înseamnă că banii tăi sunt în siguranță chiar dacă banca intră în faliment.',
    category: 'savings',
    difficulty: 'hard',
    points: 20,
  },
  {
    id: 'q007',
    question: 'Ce este un ETF (Exchange Traded Fund)?',
    options: [
      'Un cont de economii cu dobândă fixă',
      'Un fond de investiții tranzacționat la bursă care urmărește un indice',
      'Un tip de credit ipotecar',
      'O asigurare de viață',
    ],
    correct_index: 1,
    explanation: 'Un ETF este un fond de investiții care se tranzacționează la bursă ca o acțiune și urmărește un indice (ex: S&P 500). Oferă diversificare la costuri reduse și este ideal pentru investitorii începători.',
    category: 'investing',
    difficulty: 'hard',
    points: 20,
  },
  {
    id: 'q008',
    question: 'Cât timp poți amâna plata impozitului pe dividende în România?',
    options: [
      'Nu poți amâna',
      '6 luni',
      'Până la 31 mai a anului următor',
      '2 ani',
    ],
    correct_index: 2,
    explanation: 'Impozitul pe dividende în România este de 8% și trebuie declarat și plătit până la 25 mai a anului următor celui în care au fost primite dividendele (sau 31 mai pentru declarația anuală).',
    category: 'taxes',
    difficulty: 'hard',
    points: 20,
  },
  {
    id: 'q009',
    question: 'Ce înseamnă "a investi în tine însuți" din perspectivă financiară?',
    options: [
      'Cumpărarea de haine scumpe',
      'Cheltuieli pentru educație, sănătate și dezvoltare de abilități',
      'Deschiderea unui cont de investiții',
      'Economisirea banilor sub saltea',
    ],
    correct_index: 1,
    explanation: 'Investiția în propria persoană prin educație, cursuri, sănătate și dezvoltare de abilități are adesea cel mai mare randament pe termen lung, crescând potențialul de câștig și calitatea vieții.',
    category: 'investing',
    difficulty: 'easy',
    points: 10,
  },
  {
    id: 'q010',
    question: 'Care este rata impozitului pe venitul din salarii în România pentru venituri obișnuite?',
    options: ['5%', '10%', '16%', '25%'],
    correct_index: 1,
    explanation: 'Cota de impozit pe venit în România este de 10% pentru majoritatea veniturilor, inclusiv salarii. Aceasta a fost redusă de la 16% în 2018 pentru a stimula consumul și a reduce evaziunea fiscală.',
    category: 'taxes',
    difficulty: 'medium',
    points: 15,
  },
  {
    id: 'q011',
    question: 'Ce este o obligațiune (bond)?',
    options: [
      'O acțiune la o companie',
      'Un împrumut acordat unui guvern sau companie care plătește dobândă periodică',
      'Un tip de asigurare',
      'Un depozit bancar la termen',
    ],
    correct_index: 1,
    explanation: 'O obligațiune este un instrument de datorie prin care investitorul împrumută bani unui emitent (stat sau companie) care promite să plătească dobânzile periodic și să returneze principalul la scadență. Sunt mai puțin riscante decât acțiunile.',
    category: 'investing',
    difficulty: 'medium',
    points: 15,
  },
  {
    id: 'q012',
    question: 'Regula "50/30/20" în bugetare se referă la:',
    options: [
      '50% economii, 30% investiții, 20% cheltuieli',
      '50% nevoi, 30% dorințe, 20% economii',
      '50% mâncare, 30% chirie, 20% distracție',
      '50% impozite, 30% cheltuieli, 20% economii',
    ],
    correct_index: 1,
    explanation: 'Regula 50/30/20: 50% din venitul net pentru nevoi esențiale (chirie, mâncare, utilități), 30% pentru dorințe (hobby, restaurante, vacanțe) și 20% pentru economii și plata datoriilor.',
    category: 'budgeting',
    difficulty: 'easy',
    points: 10,
  },
  {
    id: 'q013',
    question: 'Ce este un scor de credit (credit scoring)?',
    options: [
      'Suma maximă pe care o poți împrumuta',
      'O notă care reflectă istoricul tău de plăți și capacitatea de rambursare',
      'Dobânda pe care o plătești la credit',
      'Numărul de credite active',
    ],
    correct_index: 1,
    explanation: 'Scorul de credit este o cifră calculată de instituții specializate (Biroul de Credit în România) care reflectă comportamentul tău de plată. Un scor bun îți oferă acces la credite cu dobânzi mai mici.',
    category: 'credit',
    difficulty: 'medium',
    points: 15,
  },
  {
    id: 'q014',
    question: 'Cât de des este recomandat să-ți revizuiești bugetul personal?',
    options: ['O dată pe an', 'O dată la 5 ani', 'Lunar', 'Niciodată dacă merge bine'],
    correct_index: 2,
    explanation: 'Revizuirea lunară a bugetului te ajută să identifici cheltuielile excesive, să ajustezi obiectivele și să rămâi pe drumul cel bun. Viața se schimbă constant, și bugetul trebuie să reflecte realitatea actuală.',
    category: 'budgeting',
    difficulty: 'easy',
    points: 10,
  },
  {
    id: 'q015',
    question: 'Ce este inflația și cum afectează economiile?',
    options: [
      'O creștere a dobânzilor bancare',
      'Creșterea generală a prețurilor care reduce puterea de cumpărare a banilor',
      'O taxă aplicată economiilor',
      'Scăderea valorii acțiunilor',
    ],
    correct_index: 1,
    explanation: 'Inflația reprezintă creșterea generală a prețurilor în timp. Dacă rata inflației este de 5% și dobânda la economii este de 3%, puterea reală de cumpărare a banilor scade. De aceea, investițiile care bat inflația sunt importante.',
    category: 'savings',
    difficulty: 'medium',
    points: 15,
  },
  {
    id: 'q016',
    question: 'Care este avantajul principal al Pilonului III de pensie în România?',
    options: [
      'Este obligatoriu pentru toți angajații',
      'Contribuțiile sunt deductibile fiscal până la 400 EUR/an',
      'Oferă pensie dublă față de stat',
      'Nu există limite de vârstă',
    ],
    correct_index: 1,
    explanation: 'Contribuțiile la Pilonul III (pensie privată facultativă) sunt deductibile fiscal până la echivalentul a 400 EUR/an. Aceasta înseamnă că reduci impozitul plătit și economisești simultan pentru pensie.',
    category: 'taxes',
    difficulty: 'hard',
    points: 20,
  },
  {
    id: 'q017',
    question: 'Ce este "efectul de levier" (leverage) în investiții?',
    options: [
      'Economisirea treptată a banilor',
      'Utilizarea banilor împrumutați pentru a amplifica potențialul de câștig (și pierdere)',
      'Diversificarea portofoliului',
      'Plata anticipată a creditelor',
    ],
    correct_index: 1,
    explanation: 'Levierul financiar implică folosirea fondurilor împrumutate pentru investiții, amplificând atât câștigurile potențiale, cât și pierderile. Este o strategie riscantă recomandată doar investitorilor cu experiență.',
    category: 'investing',
    difficulty: 'hard',
    points: 20,
  },
  {
    id: 'q018',
    question: 'Care este diferența dintre un card de debit și unul de credit?',
    options: [
      'Nu există nicio diferență',
      'Cardul de debit folosește banii din cont, cel de credit împrumută bani de la bancă',
      'Cardul de credit nu are dobândă',
      'Cardul de debit oferă cashback',
    ],
    correct_index: 1,
    explanation: 'Cardul de debit accesează direct banii din contul tău bancar. Cardul de credit îți permite să cheltuiești bani pe care îi vei rambursa mai târziu. Dacă nu plătești integral soldul lunar, se aplică dobânzi adesea ridicate (15-25% pe an).',
    category: 'credit',
    difficulty: 'easy',
    points: 10,
  },
  {
    id: 'q019',
    question: 'Cât reprezintă contribuțiile sociale totale (CASS + CAS) din salariul brut al unui angajat în România?',
    options: ['15%', '25%', '35%', '45%'],
    correct_index: 2,
    explanation: 'În România, contribuțiile sociale ale angajatului sunt: CAS (pensii) = 25% și CASS (sănătate) = 10%, totalizând 35% din salariul brut. Plus impozitul pe venit de 10%, diferența dintre brut și net poate fi semnificativă.',
    category: 'taxes',
    difficulty: 'hard',
    points: 20,
  },
  {
    id: 'q020',
    question: 'Ce înseamnă "lichiditate" în contextul financiar?',
    options: [
      'Suma totală a economiilor',
      'Capacitatea de a transforma rapid un activ în bani fără pierdere semnificativă de valoare',
      'Dobânda la depozite',
      'Numărul de tranzacții pe lună',
    ],
    correct_index: 1,
    explanation: 'Lichiditatea se referă la cât de rapid și ușor poți converti un activ în numerar. Banii în cont curent au lichiditate maximă, pe când o casă sau investiție în startup are lichiditate scăzută. Un portofoliu echilibrat are și active lichide.',
    category: 'investing',
    difficulty: 'medium',
    points: 15,
  },
  {
    id: 'q021',
    question: 'Ce este "compound interest" pe o perioadă de 10 ani dacă investești 10.000 RON la 7% annual?',
    options: ['7.000 RON profit', '9.671 RON profit', '17.000 RON total', 'Aproximativ 19.671 RON total'],
    correct_index: 3,
    explanation: 'Cu dobânda compusă de 7% annual, 10.000 RON devin aproximativ 19.671 RON după 10 ani (aproape dublul sumei inițiale). Formula: 10.000 × (1+0.07)^10 ≈ 19.671. Puterea compunerii este enormă pe termene lungi!',
    category: 'savings',
    difficulty: 'hard',
    points: 20,
  },
  {
    id: 'q022',
    question: 'Care este scopul Biroul de Credit din România?',
    options: [
      'Acordarea de credite persoanelor fizice',
      'Colectarea și gestionarea informațiilor despre comportamentul de plată al debitorilor',
      'Reglementarea dobânzilor bancare',
      'Asigurarea depozitelor bancare',
    ],
    correct_index: 1,
    explanation: 'Biroul de Credit centralizează informații despre istoricul de plăți al persoanelor care au accesat produse de credit. Băncile consultă aceste date pentru a evalua riscul de creditare. Plătind la timp, îți construiești un scor pozitiv.',
    category: 'credit',
    difficulty: 'medium',
    points: 15,
  },
]
